### ISSUE TITLE
Request for Access to ALG Algorithm Code

### ISSUE THREAD

**Issue by Guan-JW** [cwida/ALP#1]
Hi there.

I'm very interested in the ALG algorithm. I've read your paper, and I'd like to give running the code a try. I was directed to this webpage, but I found it empty. Could you please let me know how to obtain the code?

Best

**Comment by lkuffo** [comment]
Hi Guan,
Thanks for your interest in ALP.
Unfortunately we are still working in our standalone code and our compression API for it to be user friendly and up to the standard (we were surprised by the paper being published a bit ahead of our schedule)

However, we do have already [an implementation of ALP](https://github.com/duckdb/duckdb/pull/9635) written inside DuckDB, using DuckDB compression API. So, you could ran some tests with ALP using DuckDB for the time being (there are ways to force the use of a specific compression scheme in duckdb). 

For instance, I can redirect you to some of the main code pieces of this implementation within DuckDB code base, in case you want to dive deep on how it is implemented:   
- [ALP core](https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/storage/compression/alp/algorithm/alp.hpp) algorithm 
- [ALP storage](https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/storage/compression/alp/alp_compress.hpp#L131) of compressed data (how data is stored in disk)
- [ALPrd core](https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/storage/compression/alprd/algorithm/alprd.hpp) algorithm
- [ALPrd storage](https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/storage/compression/alprd/alprd_compress.hpp#L145) of compressed data (how data is stored in disk)
- [A basic example](https://github.com/duckdb/duckdb/blob/main/benchmark/micro/compression/alp/alp_read.benchmark) on how to load data in DuckDB forcing ALP to be used as compression method

And also, in the [original PR](https://github.com/duckdb/duckdb/pull/9635) you may find additional information regarding on how it was implemented, the storage layout, etc.

We will update you as soon as our standalone code meant to be used as a C++ lib is fully available
Best,

**Comment by Guan-JW** [comment]
Thank you for your prompt response and for providing alternative options for testing ALP. I'll give it a try using DuckDB. Look forward to hearing updates on the availability of your standalone code.

Best,
Jiawei

**Comment by lkuffo** [comment]
Hi there @Guan-JW ,
Small update on this: We have now published our source code 

Thanks for the wait :)

**Comment by Guan-JW** [comment]
Cool! Thank you for the update and for sharing the source code!
I appreciate your efforts and look forward to trying it.

Best regards,
Jiawei
