### ISSUE TITLE
Suggestions for encoding floats with varying length?

### ISSUE THREAD

**Issue by lyp-bobi** [cwida/ALP#2]
Hi there,

I'm working on processing trajectories (which includes a sequence of (x,y,t) coordinates) and I'm considering using ALP to compress my coordinates. However I meet some problems, and I wonder if I could get some help here.

The major problem is that the implementation seems to only support float number arrays with dimension 1024. I'm not sure how should I encode a vector with, for example, 1524 dimensions. Should I compress the first 1024 floats, and left the other 500 uncompressed? Or should I encode them together? (however I found that you write "ALP Vector size (We recommend against changing this; it should be constant)", so I think I should not do it)

I'm also not quite sure about what is the best way to use ALP in my data. For example, if i have a trajectory [(x1,y1,t1), (x2,y2,t2),...., (xn,yn,tn)]，the x and y are lat/lon and t is unix timestamp. Should I store ALP(x1,x2,...xn)+ ALP(y1,y2,...,yn) + ALP(t1, t2,...,tn), or should I store ALP(x1,x2,...xn, y1,y2,...,yn, t1, t2,...,tn), or should i store ALP(x1,y1,t1, x2, y2,t2,..., xn, yn, tn)?  

 In addition, the length n of my trajectories can range from 2 to several thousands, and I think i should only use ALP for long trajectories whose n is big enough.  What value of n do you think I should start to use ALP for compression? Or anyway, does ALP suit this senario?

I'm looking forward to your response. Thanks :D

**Comment by azimafroozeh** [comment]
Hi:
1. how should I encode a vector with, for example, 1524 dimensions?
      - ALP is optimized to decode and encode a batch of 1024. Probably, you have a lot of these 1524 batches. My recommendation is to have a wrapper around ALP that checks if you have the next 1524 data decoded; if not, call ALP and decode 1024 till you buffered 1524. 
2. Should I store ALP(x1,x2,...xn)+ ALP(y1,y2,...,yn) ...?
      - I recommend your first solution, ALP(x1,x2,...xn)+ ALP(y1,y2,...,yn). This is because x data comes from the same source and has more potential to be compressed. If you interleave data from different sources, x and y, I expect the compression ratio to drop sharply.
3. the length n of my trajectories can range from 2 to several thousand?
      - indeed, there is no point in compressing a small amount of data.

**Comment by lkuffo** [comment]
Hi,
I would like to add up to Azim's message by saying that in the case you have 1524 values to encode, you can compress 1024 and then either leave the other 500 uncompressed, or use a similar strategy to [the one we use in our example compression API](https://github.com/cwida/ALP/blob/main/include/alp/compressor.hpp#L113) which fills the incomplete array to 1024 values. You can also store it uncompressed; specially if you only have 1 value left. All in all, this could be managed in a case to case basis. 

However, it is important to note your 3rd point: several thousands values is not worth to compress. **Unless** you have thousands of these trajectories. Then you could, for instance, merge all your trajectories in one long array of the same dimensions. And compress that long sequence. This would work beautifully with ALP. Then, if you also store the length of your trajectories (or even better if its fixed) you can quickly scan and skip through them. 
(You will still have the same problem of not having 1024 values at the end but at that point it will affect little on the compression ratio whatever you do with these).

Best,
