### ISSUE TITLE
Request for Assistance with Linker Error during Build Process

### ISSUE THREAD

**Issue by tsctsch** [cwida/ALP#22]
[output.txt](https://github.com/user-attachments/files/17449690/output.txt)

Dear Mr.AZIM AFROOZEH,

I am currently facing an issue during the build process of my project. After running the make command, I encounter the following error:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have attached the full error output in the output.txt file for your reference. Could you please assist me in identifying the cause of this issue and suggest a solution?

Thank you in advance for your help!

Best regards,
Tian Sanchuan

**Comment by azimafroozeh** [comment]
Thank you for reaching out. It appears that the issue is a linker error caused by several undefined references, particularly related to the C++ Standard Library (e.g., std::basic_ios, std::basic_string, and std::basic_streambuf). My guess is that your project is not correctly linking the standard C++ library. Could you provide the CMake configuration or build setup you're using for the repository? It would be easier for me to help with that information.

Best regards,
Azim Afroozeh

**Comment by tsctsch** [comment]
Dear Mr.AZIM AFROOZEH,

I hope this message finds you well. I am currently working on the ALP project and encountered several issues during the make process. I wanted to seek your guidance on how to resolve these errors.

During compilation, I received numerous warnings and errors, including:

Warnings related to #pragma GCC diagnostic pop: There were warnings indicating that #pragma GCC diagnostic pop could not pop due to no matching push. This suggests that I may not have properly paired these directives.

Undefined type uint32_t: The code could not recognize uint32_t, which I believe can be resolved by including the necessary header files, such as <cstdint>.

Non-void function missing return value: There was a warning about a non-void function not returning a value in all control paths. I will need to review the function to ensure all execution paths return a value.

Implicitly deleted move constructor: I encountered an error indicating that the move constructor for the BlockRelation class was implicitly deleted because it contains a std::mutex. I understand that I may need to explicitly delete or redefine this constructor.

Unqualified calls to std::move: Several warnings pointed out unqualified calls to std::move, which should be addressed by adding the std:: prefix.

I have made some preliminary attempts to address these issues but would appreciate your insights or any additional steps you recommend to resolve these compilation errors effectively.

Thank you for your assistance. I look forward to your reply.

Best regards,
Tian Sanchuan
Attached are the error messages:
[ 28%] Building CXX object publication/source_code/bench_end_to_end/CMakeFiles/common.dir/src/common/algebra/Operators.cpp.o
In file included from /root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:1:
In file included from /root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Operators.hpp:4:
In file included from /root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:4:
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Mmap.hpp:359:27: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
  359 | #pragma GCC diagnostic pop
      |                           ^
In file included from /root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:1:
In file included from /root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Operators.hpp:4:
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:35:27: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
   35 | #pragma GCC diagnostic pop
      |                           ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:42:27: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
   42 | #pragma GCC diagnostic pop
      |                           ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:84:2: warning: non-void function does not return a value in all control paths [-Wreturn-type]
   84 |         }
      |         ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:108:2: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
  108 |         BlockRelation(BlockRelation&&)      = default;
      |         ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:172:13: note: move constructor of 'BlockRelation' is implicitly deleted because field 'insertMutex' has a deleted move constructor
  172 |         std::mutex insertMutex;
      |                    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_mutex.h:107:5: note: 'mutex' has been explicitly marked deleted here
  107 |     mutex(const mutex&) = delete;
      |     ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/runtime/Database.hpp:108:40: note: replace 'default' with 'delete'
  108 |         BlockRelation(BlockRelation&&)      = default;
      |                                               ^~~~~~~
      |                                               delete
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:10:26: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   10 |     : Operator(n), child(move(c)) {
      |                          ^
      |                          std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:15:25: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   15 |     : Operator(n), left(move(l)), right(move(r)) {
      |                         ^
      |                         std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:15:41: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   15 |     : Operator(n), left(move(l)), right(move(r)) {
      |                                         ^
      |                                         std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:21:62: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   21 | Map::Map(std::unique_ptr<Operator> c) : UnaryOperator("map", move(c)) {}
      |                                                              ^
      |                                                              std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:23:30: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   23 |     : UnaryOperator("print", move(c)), attributes(move(att)) {}
      |                              ^
      |                              std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:23:51: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   23 |     : UnaryOperator("print", move(c)), attributes(move(att)) {}
      |                                                   ^
      |                                                   std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:26:34: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   26 |     : BinaryOperator("hashjoin", move(build), move(probe)) {}
      |                                  ^
      |                                  std::
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Operators.cpp:26:47: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
   26 |     : BinaryOperator("hashjoin", move(build), move(probe)) {}
      |                                               ^
      |                                               std::
13 warnings generated.
[ 28%] Building CXX object publication/source_code/bench_end_to_end/CMakeFiles/common.dir/src/common/algebra/Types.cpp.o
In file included from /root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Types.cpp:1:
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:39:4: error: unknown type name 'uint32_t'
   39 |    uint32_t size = 0;
      |    ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:40:4: error: unknown type name 'uint32_t'
   40 |    uint32_t precision = 0;
      |    ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:42:12: error: unknown type name 'uint32_t'
   42 |    Numeric(uint32_t size, uint32_t precision);
      |            ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:42:27: error: unknown type name 'uint32_t'
   42 |    Numeric(uint32_t size, uint32_t precision);
      |                           ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:49:4: error: unknown type name 'uint32_t'
   49 |    uint32_t size = 0;
      |    ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:52:9: error: unknown type name 'uint32_t'
   52 |    Char(uint32_t size);
      |         ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:57:4: error: unknown type name 'uint32_t'
   57 |    uint32_t size = 0;
      |    ^
/root/ALP/publication/source_code/bench_end_to_end/include/common/algebra/Types.hpp:60:12: error: unknown type name 'uint32_t'
   60 |    Varchar(uint32_t size);
      |            ^
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Types.cpp:34:10: error: out-of-line definition of 'Numeric' does not match any declaration in 'algebra::Numeric'
   34 | Numeric::Numeric(uint32_t s, uint32_t p) : size(s), precision(p) {}
      |          ^~~~~~~
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Types.cpp:47:7: error: out-of-line definition of 'Char' does not match any declaration in 'algebra::Char'
   47 | Char::Char(uint32_t s) : size(s) {}
      |       ^~~~
/root/ALP/publication/source_code/bench_end_to_end/src/common/algebra/Types.cpp:56:10: error: out-of-line definition of 'Varchar' does not match any declaration in 'algebra::Varchar'
   56 | Varchar::Varchar(uint32_t s) : size(s) {}
      |          ^~~~~~~
11 errors generated.
make[2]: *** [publication/source_code/bench_end_to_end/CMakeFiles/common.dir/build.make:90: publication/source_code/bench_end_to_end/CMakeFiles/common.dir/src/common/algebra/Types.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3266: publication/source_code/bench_end_to_end/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by azimafroozeh** [comment]
Hi Tian,

Thanks for the information so far. To get a clearer picture, could you share the output of the CMake configuration or specify the Clang version you’re using? This will help me identify the root of the issue. If you’re unsure how to provide this information, I’d be happy to guide you through the process—just let me know.

Best regards.

**Comment by azimafroozeh** [comment]
Thanks for the info! A couple of things:

I noticed a CMake warning about a missing source or binary directory. To avoid this warning, try using cmake -S /path/to/source -B /path/to/build to specify these directories explicitly.

To build the publication benchmarks for ALP, you can use this script: [master_script.sh](https://github.com/cwida/ALP/blob/main/publication/master_script/master_script.sh). You can run the script directly. Please share the output from running it.

If the second step doesn’t work, please try commenting out [this line](https://github.com/cwida/ALP/blob/eab5d9ec2bfe456b3ff8b7215af26d86d13e072e/publication/source_code/CMakeLists.txt#L29) to disable building the ALP end-to-end benchmarks, as this might be causing the issue. We can address that part later."

**Comment by tsctsch** [comment]
Thank you for your guidance on the CMake warnings and the ALP benchmarks. I have run the master_script.sh and saved the output in a file named [output.txt](https://github.com/user-attachments/files/17585446/output.txt). However, I encountered some errors during the process. I would appreciate your assistance in resolving these issues.

Thank you again for your support!

**Comment by peterboncz** [comment]
Hello there. Please do take a look at the errors, it says things like:

- bash: /root/complete_binaries: Is a directory
- fatal: unable to access 'https://github.com/cwida/ALP.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
- fatal: unable to access 'https://github.com/oneapi-src/oneTBB.git/': Failed to connect to github.com port 443 after 134481 ms: Couldn't connect to server

and evenuaally fails with:
- include could not find requested file: /root/BENCH_PED/test/local.cmake

But maybe first make sure you have a clean machine that is connected to the internet

**Comment by tsctsch** [comment]
Thank you for your insights regarding the errors I encountered. I have resolved the network connection issue, but I’m still facing some other problems.

I have saved the latest output in a file named [output1.txt](https://github.com/user-attachments/files/17586942/output1.txt) for your review. I would appreciate any assistance you can provide to help resolve these remaining issues.

Thank you for your continued support!

**Comment by azimafroozeh** [comment]
From the output logs, it appears the repository is now building successfully, with only a few test failures remaining. Most of these failures seem related to missing ALP data or data not being in the correct path. You can check [this guide](https://github.com/cwida/ALP/blob/main/BENCHMARKING.md#downloading-data) for instructions on downloading and setting the correct path for the data files.

**Comment by azimafroozeh** [comment]
We have rewritten the scripts that run all benchmarks for the publication.
Please check [this pull request](https://github.com/cwida/ALP/pull/27).
Feel free to reopen this issue if the script still does not work for you.
