### ISSUE TITLE
error: Expected equality of these values

### ISSUE THREAD

**Issue by SeeYouLaterPromise** [cwida/ALP#24]
When I tested the new dataset, which has large nunber of siginicands I met:

alp/benchmarks/bench_compression_ratio/bench_alp_compression_ratio.cpp(293): error: Expected equality of these values:
  stt.scheme
    Which is: 1-byte object <01>
  alp::Scheme::ALP_RD
    Which is: 1-byte object <00>
    
Can you give me some guidance?

**Comment by azimafroozeh** [comment]
Thanks for the issue! Could you share a sample of the dataset that produced this error?

**Comment by SeeYouLaterPromise** [comment]
![Uploading sample.png…]()
Sure! I have the initial understanding of your project, that is, for high precision datasets (i.e., data have large number of siginificands) should use RD (Your samples such as POI-lat and POI-lan,  can work through this way), but this time doesn't work for my test dataset named ShapeletSim_TEST.csv. The text of test samples is as follows:

-1.7364531
1.3814366
1.438711
1.155993
0.010562082
0.35199697
-0.47133151
-1.028986
0.7322407
-1.0070036
0.23961036
-0.11736983
1.6188454
0.87447891
0.17712031
0.85670133
1.4895166
-0.028453834
1.1957284
-0.19157237
1.1785826
-0.51153377
0.8408226
1.3257452
0.39198864
1.7005837
1.3379561
0.41338141
-0.25926056
0.46950101
0.29511222
1.1901688
0.68518363

**Comment by azimafroozeh** [comment]
I've tried replicating the issue; you can review it at [this link](https://github.com/cwida/ALP/tree/issue_24). The data isn’t highly precise and should be compressed by ALP directly rather than by ALP_RD. This data could be encoded in 32 bits, which would provide a 2x compression ratio.

**Comment by SeeYouLaterPromise** [comment]
Thank you for your generous helping! According to your reply, I knew that the error ouccurred due to the wrong scheme I chose (should be ALP). The fact I chose ALP_RD is that I found ALP cannot test the dataset properly, in this way, I turned to ALP_RD, cus I my mind, RD can help solve the issue ALP cannot.

I will show the error message I met:
See the dataset of ShapesAll_TEST's size: 307200
D:\MicrosoftVisualStudio\VC\Tools\MSVC\14.41.34120\include\vector(1889) : Assertion failed: vector subscript out of range
Process finished with exit code -1073740791 (0xC0000409)

The corresponding test dataset is as follows:
[ShapesAll_TEST.csv](https://github.com/user-attachments/files/17595039/ShapesAll_TEST.csv)

**Comment by SeeYouLaterPromise** [comment]
I figured out the error reason behind:

in the "encoder.hpp" file,
line 395:

		if (stt.k_combinations > 1) { // Only if more than 1 found top combinations we sample and search
			find_best_exponent_factor_from_combinations(
			    stt.best_k_combinations, stt.k_combinations, input_vector, stt.vector_size, stt.fac, stt.exp);
		}
		else if (stt.best_k_combinations.size()) {
			stt.exp = stt.best_k_combinations[0].first;
			stt.fac = stt.best_k_combinations[0].second;
+		} else {
+			std::cout << "The fact indicates None k_combination!!!" << std::endl;
+			std::cout << "best_k_combinations size(): " << stt.best_k_combinations.size() << std::endl;
+		}
-		else {
-			stt.exp = stt.best_k_combinations[0].first;
-			stt.fac = stt.best_k_combinations[0].second;
-		}


I found the error led by out of bound index array here! 
I just enhance the robustness of the logical code, I am not sure it would lead some terrible influence, please give me some instructions.
moreover, I found you re-init each 100 group, can you also give me some instructions for this intention?

**Comment by azimafroozeh** [comment]
I cannot reproduce your error. However, I see that you have 300 * 1024 = 307200 values. To encode this amount of data, you have two options: either adjust ALP's ROWGROUP_SIZE to 300 vectors, which you can modify here: https://github.com/cwida/ALP/blob/eab5d9ec2bfe456b3ff8b7215af26d86d13e072e/include/alp/config.hpp#L13, or use ALP three times with a row group size of 100.

We reinitialize ALP every 100 vectors (one row group in ALP) to better adapt to the data and select optimal parameters. File formats like Parquet use row groups, where a partition of data is encoded at once. In ALP, the row group size is set to 100 vectors of 1,024 values each. By reinitializing ALP every 100 vectors, we can fine-tune its parameters to suit the data in each row group.

Regarding your options, if your data is relatively homogeneous across three groups of 100 vectors, changing the row group size to 300 is efficient enough in terms of compression ratio. However, if there is significant variation, the second option—reinitializing ALP after each 100-vector block—would allow it to adjust its parameters more effectively for each row group.

**Comment by SeeYouLaterPromise** [comment]
Thank you for the detailed instruction for me. However, I actually met the error when testing the [ShapesAll_TEST.csv](https://github.com/user-attachments/files/17595039/ShapesAll_TEST.csv) file: The error lies in the last group (300-th group), where assertion abortion works due to the visit for empty vector (stt.best_k_combination).

**Comment by azimafroozeh** [comment]
Check this commit [here](https://github.com/cwida/ALP/commit/03f12512534fca2020649ddc576f47504ddc168c). I added your dataset and modified the ALP_ROWGROUP_SIZE to 300. The resulting compression ratios are as follows:
```issue_24_replicated_data, 32.09, 1, 100
issue_24_actual_data, 33.57, 1, 300```
