### ISSUE TITLE
Where is the Elf algorithm reproduced?

### ISSUE THREAD

**Issue by LeeSure5986** [cwida/ALP#25]
Hello,

I have successfully executed the script and reproduced the experimental results. However, the experimental result figure figure_1_Speed.png does not include the results of the Elf algorithm, nor did I find any code for reproducing the Elf algorithm in your projects. Could you please provide the code for reproducing the Elf algorithm?

Best regards,
Li Shuo

**Comment by lkuffo** [comment]
Hi,
To benchmark Elf, we ran experiments using [their codebase](https://github.com/Spatio-Temporal-Lab/elf). We didn't have the time to re-implement Elf in C++ (as Elf was published just a few days before the deadline to submit ours).

Currently, we are trying to incorporate Elf Java code into our codebase to achieve full reproducibility of the results reported in the ALP paper, however, it is still WIP.

**Comment by lkuffo** [comment]
We have added Elf benchmarks (both speed and compression ratio) to our reproducibility suite. 

To run Elf benchmarks you must have Java 1.8 installed and Maven pointing to that Java version. Then, you can run Elf benchmarks as a standalone test:
```sh
mvn -f "./publication/source_code/extern/elf/pom.xml" test
```
After the test finish you will see the results under `publication/compression_ratio_result/double/elf.csv` for compression ratios, and `publication/results/i4i_4xlarge/elf_raw.csv` for micro-benchmarks of decompression/compression speed (measured in tuples processed per CPU cycle).

To incorporate Elf we took [the branch](https://github.com/Spatio-Temporal-Lab/elf/tree/vldb2023-release) of their code which we used for our initial benchmarks, added a FileReader to be able to read binary files of doubles and changed the BlockSize from 1000 to 1024.  PR: #30
