### ISSUE TITLE
A Bug when compressing only one vector

### ISSUE THREAD

**Issue by lyp-bobi** [cwida/ALP#3]
To reproduce the bug, I set `size_t tuples_count = 1;` in `simple_compress.cpp`, and received a segmentation fault.

I think it may be because the bit-width is set to 25 and the compressed size exceeds 8192. In addition, some other things seem to not work well.

It is a corner case when `tuples_count=1`, but I think this bug might also exist when `tuples_count=1025`, etc.

**Comment by azimafroozeh** [comment]
Thanks, I will take a look into it.

**Comment by lyp-bobi** [comment]
> I extended the simple_compress to `[1, 1025]`. However, I cannot reproduce the segmentation fault.

some of my memory variables:

```
tuples_count = {size_t} 1
out_buffer_size = {size_t} 8104
uncompressed_size = {size_t} 8
in = {double [1]} 
out = {uint8_t [8104]} 
compressor = {alp::AlpCompressor<double, false>} 
 stt = {alp::state} 
  scheme = {alp::SCHEME} alp::SCHEME::ALP
  vector_size = {uint16_t} 1
  exceptions_count = {uint16_t} 1024
  sampled_values_n = {size_t} 1
  k_combinations = {uint16_t} 1
  best_k_combinations = {std::vector<std::pair<int, int>>} 
  exp = {uint8_t} 0 '\000'
  fac = {uint8_t} 0 '\000'
  bit_width = {alp::bw_t} 0 '\000'
  for_base = {int64_t} 0
  right_bit_width = {alp::bw_t} 0 '\000'
  left_bit_width = {alp::bw_t} 0 '\000'
  right_for_base = {uint64_t} 0
  left_for_base = {uint16_t} 0
  left_parts_dict = {uint16_t [8]} 
  actual_dictionary_size = {uint8_t} 0 '\000'
  actual_dictionary_size_bytes = {uint32_t} 0
  left_parts_dict_map = {std::unordered_map<unsigned short, unsigned short>} 
 storer = {alp::storer::MemStorer<false>} 
 input_vector = {double [1024]} 
 exceptions = {double [1024]} 
 sample_array = {double [1024]} 
 encoded_integers = {int64_t [1024]} 
 alp_encoded_array = {int64_t [1024]} 
 exceptions_rd = {uint16_t [1024]} 
 exceptions_position = {uint16_t [1024]} 
 alp_bp_size = {uint64_t} 0
 left_bp_size = {uint64_t} 0
 right_bp_size = {uint64_t} 0
 right_parts = {alp::AlpCompressor<double, false>::EXACT_TYPE [1024]} 
 right_parts_encoded = {alp::AlpCompressor<double, false>::EXACT_TYPE [1024]} 
 left_parts_encoded = {uint16_t [1024]} 
 left_parts = {uint16_t [1024]} 
 right_for_base = {alp::AlpCompressor<double, false>::EXACT_TYPE} 0
compressed_size = {size_t} 10254
compression_ratio = {double} 0.00078018334308562517
decompressed_buffer_size = {size_t} 1024
```
as we can see, `out_buffer_size = {size_t} 8104` and `compressed_size = {size_t} 10254`, so I guess there must be a segmentation fault.

I'm not quite sure how or whether we can reproduce it with 1025...but I guess you can get some memory problem if you build this project with some memory checkers such as asan?

**Comment by azimafroozeh** [comment]
To reproduce the error, could you create a csv file out of the dataset ALP fails to encode/decode?. An example of such as csv file is here https://github.com/cwida/ALP/blob/main/data/edge_case/edge_case.csv

**Comment by lyp-bobi** [comment]
> To reproduce the error, could you create a csv file from the dataset ALP fails to encode/decode? An example of such csv file is here https://github.com/cwida/ALP/blob/main/data/edge_case/edge_case.csv

As I just said, I just simply set `size_t tuples_count = 1` in `simple_compress.cpp`, so the case is apparently a single-element vector of  `[204.92]`, I think you will also get this value as you use a constant random seed.

**Comment by lyp-bobi** [comment]
I figured it out. The problem comes from `if (non_exceptions_count < 2) { continue; }`, it makes `stt.exp = 0` and `stt.fac = 0`, and which further makes `stt.exceptions_count = 1024`(this might depend on different architecture?), thus making the `size_t out_buffer_size =
	    (tuples_count * sizeof(double)) + 8096; // We leave some headroom in case of negative compression` not enough. The negative compression may at most take 1024*(EXCEPTION_SIZE_BYTES+EXCEPTION_POSITION_SIZE_BYTES)=10240 bytes more. Which lead to Segmentation fault.

**Comment by azimafroozeh** [comment]
Thank you for your debugging. I was unable to reproduce the issue you mentioned. However, you are correct that the 8096 may not always work if there are exceptions. I have updated the example accordingly. Please keep in mind that this is just a demonstration of how ALP can be used, and memory handling should be managed by the user of ALP.
