### ISSUE TITLE
ALP stream specification

### ISSUE THREAD

**Issue by Eclesia** [cwida/ALP#32]
Hello,

I am working on GIS tools, and played with various compression techniques over the years, rle, dict, xor, lz4, zstd, wavelet..... and others. So far zstd is the most efficient on scientific float datas.

ALP seems very promising and I would like to use it but it is a compression library.

Compression libs have the bad habit of becoming unmaitained/obsolete after a few years. 

Compression specification like Deflate or LZ have and will live for many many more years even if they are not great because many implementation exist and the bitstream remains unchanged.

Do you plan on making a bitstream specification for ALP with pseudo code encoder/decoder ?

**Comment by peterboncz** [comment]
We would be happy to review your PR!

**Comment by Eclesia** [comment]
> We would be happy to review your PR!

I see, you must have a lot of user requests. Sorry for bothering you with this idea.
